### ISSUE TITLE
could boost context be optional

### ISSUE THREAD

**Issue by jwaterloo** [BoostGSoC14/boost.http#11]
could boost context be optional
on mingw, context is not built by default because context requires masm to be on the path
...
I was able to work around this issue by getting masm and rebuilding boost but is MASM is optional, than context is option in boost and as such should preferably be optional in any libraries that bepend upon it

**Comment by vinipsmaker** [comment]
> could boost context be optional

Surely. It's only used on tests and examples. The library itself doesn't use it. But then, you'll need to write your own example.
