### ISSUE TITLE
Invalid Request and Response 400

### ISSUE THREAD

**Issue by fcharlie** [BoostGSoC14/boost.http#46]
When use request invalid encoding url, spawn exit self,
![2016-08-29 16-17-17](https://cloud.githubusercontent.com/assets/6904176/18045173/16e06cce-6e04-11e6-80f5-8f4f48cabe87.png)

I think, when parse error, should response **400 Bad Request**

**Comment by vinipsmaker** [comment]
There was code to reply invalid messages: https://github.com/BoostGSoC14/boost.http/blob/c0de705e6f0c494d382b3dc1e72e317683edd21f/include/boost/http/socket-inl.hpp#L646

It got removed once I replaced the NodeJS parser. I need to add it again: https://github.com/BoostGSoC14/boost.http/blob/72b06c8d326a686af89d7ae6754a632687d7cf15/include/boost/http/socket-inl.hpp#L657
