### ISSUE TITLE
Compile error, Visual Studio

### ISSUE THREAD

**Issue by vinniefalco** [BoostGSoC14/boost.http#48]
I ran CMake on the test directory, opened up the solution, and tried to build. I get this error in many places:

**2>D:\lib\boost_1_61_0\boost/asio/detail/socket_types.hpp(24): fatal error C1189: #error:  WinSock.h has already been included**

**Comment by vinipsmaker** [comment]
Fixed by https://github.com/BoostGSoC14/boost.http/commit/c5d2ba4987a17ca0235a6fcd0c277d7b9fbfc9b0

Don't know why AppVeyor wasn't getting this error. But it doesn't matter now as I got a Windows machine just to run Boost.Http tests.
