### ISSUE TITLE
Build failing with boost 1.56

### ISSUE THREAD

**Issue by whoshuu** [BoostGSoC14/boost.http#9]
Tried building your library with boost 1.56 installed on my system, but it had trouble resolving the overloaded constructors in `flat_multimap` in the [socket tests](https://github.com/BoostGSoC14/boost.http/blob/c43191d20ad1209ab9a5bcab764b43d1732f7fd0/test/socket.cpp#L141).

Took a look through the boost docs, and on 1.56, there's no `initializer_list` constructor for `flat_multimap`. That constructor first appears in 1.57.

It'd be helpful to have a note in your readme detailing the minimum boost version required to build your library. I know if/when this library is approved for boost inclusion, it'll be at a version where the minimum requirements are met, but for people trying out your library with a system boost installed, it's nice to know if an upgrade is necessary or not.

**Comment by vinipsmaker** [comment]
Thanks for sharing this information, @whoshuu. I'll update the documentation.
